version: '3.8'
services:
  postgres:
    image: postgres
    environment:
      - POSTGRES_USER=app
      - POSTGRES_PASSWORD=app
      - POSTGRES_DB=ShoppingListDb
    volumes:
      - ./volumes/data/db:/var/lib/postgresql/data
    networks:
      - slNetwork
    ports:
       - 5433:5432
networks:
  slNetwork:
    driver: bridge
  # webapp:
  #   image: mcr.microsoft.com/dotnet/core/samples:aspnetapp
  #   ports:
  #     - 80
  #     - 443
  #   environment:
  #     - ASPNETCORE_ENVIRONMENT=Development
  #     - ASPNETCORE_URLS=https://+:443;http://+:80
  #     - ASPNETCORE_Kestrel__Certificates__Default__Password=password
  #     - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
  #   volumes:
  #     - ~/.aspnet/https:/https:ro