version: '3.8'
services:
  postgres:
    build:
      context: ./
      dockerfile: Dockerfile
    environment:
      - POSTGRES_USER=app
      - POSTGRES_PASSWORD=app
      - POSTGRES_DB=ShoppingListDb
    volumes:
      - /var/lib/postgresql/data
    networks:
      - slNetwork
    ports:
       - 5433:5432
networks:
  slNetwork:
    driver: bridge